### ISSUE TITLE
Roster Netbox calling filter method w/o kwargs.

### ISSUE THREAD

**Issue by n-holmstedt** [mirceaulinic/salt-sproxy#111]
First, i've only dabbled with salt and netbox for a couple of days. Don't really know if this is a salt-sproxy issue or a salt issue?

The netbox runner function, "targets", uses the salt-module netbox's filter-method without key-word arguments. When running, this causes an error in the underlaying pynetbox filter_ method which requires kwargs. 

> salt-sproxy -l debug ti* --preview-target

or using the provided example without kwargs:

> salt-run salt.cmd netbox.filter dcim devices

> Exception occurred in runner salt.cmd: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/salt/client/mixins.py", line 374, in low
    data['return'] = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/salt/runners/salt.py", line 106, in cmd
    if fun in functions \
  File "/usr/local/lib/python3.7/site-packages/salt/modules/netbox.py", line 164, in filter_
    **__utils__['args.clean_kwargs'](**kwargs)
  File "/usr/local/lib/python3.7/site-packages/pynetbox/core/endpoint.py", line 209, in filter
    "filter must be passed kwargs. Perhaps use all() instead."
ValueError: filter must be passed kwargs. Perhaps use all() instead.

Updating the salt module to use the 'all()' method, instead of filter if no kwargs present, which seems to give me the results i'm after.

**Comment by mirceaulinic** [comment]
Hi @n-holmstedt. Can you re-run with [`--sync-modules`](https://salt-sproxy.readthedocs.io/en/latest/opts.html#cmdoption-sync-modules), i.e., `salt-sproxy -l debug ti* --preview-target --sync-modules` and confirm it works well?

**Comment by n-holmstedt** [comment]
Yup. Seems to work. 

> [DEBUG   ] Sending event: tag = salt/run/20200414142944986224/ret; data = {'fun': 'runner.proxy.execute', 'jid': '20200414142944986224', 'user': 'salt', 'fun_args': ['ti*', 'not_a_valid_command', {'progress': False, 'tgt_type': 'glob', 'preview_target': True, 'batch_size': 2, 'batch_wait': 0, 'cache_grains': False, 'cache_pillar': False, 'roster': 'netbox', 'timeout': 5, 'static': False, 'no_connect': False, 'failhard': False, 'summary': False, 'verbose': False, 'show_jid': False, 'hide_timeout': False, 'returner': '', 'target_cache': False, 'returner_config': '', 'returner_kwargs': {}, 'events': False, 'use_existing_proxy': False, 'test_ping': False, 'target_cache_timeout': 60, 'args': [], 'default_grains': {}, 'default_pillar': None, 'preload_targeting': False, 'invasive_targeting': False}], '_stamp': '2020-04-14T14:29:45.364743', 'return': ['ti430940400e460'], 'success': True}
[DEBUG   ] LazyLoaded nested.output
- ti430940400e460
[INFO    ] Runner completed: 20200414142944986224
[DEBUG   ] Closing IPCMessageClient instance
[DEBUG   ] Runner return: ['ti430940400e460']

Love the blog and your other work btw. Looking to replace some in-house company backend polling 100k dumb network elements and looking into salt atm.

**Comment by mirceaulinic** [comment]
Hey @n-holmstedt - are you able to try the code from #112 and confirm it works fine for you (without running with the `--sync-modules` option?
