### ISSUE TITLE
Question: unexpected kwargs in netmiko ConnectionHandler.

### ISSUE THREAD

**Issue by n-holmstedt** [mirceaulinic/salt-sproxy#113]
Hello again. Question regarding kwargs used in the netmiko_px proxy-module. 

`    proxy_dict = opts.get('proxy', {})`
` ...`
`    log.info(netmiko_connection_args)`

This causes grains data, as well as pillar data, to be loaded, and i'm not sure why. 

> [INFO    ] {'device_type': 'huawei_vrpv8', 'host': 'salt-dummy', 'username': 'huawei', 'password': 'huawei', 'grains': {'salt': {'role': 'proxy'}, 'netbox': {'id': 1, 'name': 'ti430940400e460', 'display_name': 'ti430940400e460', 'device_type': {'id': 1, 'manufacturer': {'id': 1, 'name': 'Huawei', 'slug': 'huawei'}, 'model': 'Quidway S5352C-EI', 'slug': 'quidway-s5352c-ei', 'display_name': 'Huawei Quidway
S5352C-EI'}, 'device_role': {'id': 1, 'name': 'Aggregation', 'slug': 'aggregation'}, 'tenant': None, 'platform': None, 'serial': '12325123123', 'asset_tag': None, 'site': {'id': 1, 'name': 'testsite1', 'slug': 'testsite1'}, 'rack': None, 'position': None, 'face': None, 'parent_device': None, 'status': {'value': 'active', 'label': 'Active', 'id': 1}, 'primary_ip': {'id': 6, 'family': 4, 'address': '172.29.0.3/16'}, 'primary_ip4': {'id': 6, 'family': 4, 'address': '172.29.0.3/16'}, 'primary_ip6': None, 'cluster': None, 'virtual_chassis': None, 'vc_position': None, 'vc_priority': None, 'comments': '', 'local_context_data': None, 'tags': [], 'custom_fields': {}, 'config_context': {}, 'created': '2020-04-08', 'last_updated': '2020-04-14T19:55:33.893383Z'}}}

> Process ti430940400e460:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
    **opts
  File "/usr/local/lib/python3.7/site-packages/salt_sproxy/_runners/proxy.py", line 593, in salt_call
    sa_proxy = StandaloneProxy(opts, unreachable_devices)
  File "/usr/local/lib/python3.7/site-packages/salt_sproxy/_runners/proxy.py", line 425, in __init__
    self.gen_modules()
  File "/usr/local/lib/python3.7/site-packages/salt_sproxy/_runners/proxy.py", line 362, in gen_modules
    proxy_init_fn(self.opts)
  File "/usr/local/lib/python3.7/site-packages/salt/proxy/netmiko_px.py", line 245, in init
    connection = ConnectHandler(**netmiko_connection_args)
  File "/usr/local/lib/python3.7/site-packages/netmiko/ssh_dispatcher.py", line 246, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'grains'
ERROR: Minions returned with non-zero exit code

Modifying the netmiko_px, pop'ing the grains from the kwargs fixes the problem for me: 
> / # salt-sproxy '*' netmiko.send_command "display lldp neighbor" use_textfsm=True  --timeout 10
ti430940400e460:
    |_
      ----------
      capabilities:
          bridge router
      chassis_id:
          04f9-3885-2840
      local_interface:
          XGigabitEthernet0/1/1
...

Is this due to some faulty configuration or arguments on my part?

**Comment by mirceaulinic** [comment]
Hi @n-holmstedt. I think this is a small bug I suspected for some time. Would you be able to patch it locally and confirm if that fixes it? After this line https://github.com/mirceaulinic/salt-sproxy/blob/develop/salt_sproxy/_runners/proxy.py insert a similar one `self.opts['pillar']['proxy'].pop('grains', None)`. Curious if that's fixing it

**Comment by n-holmstedt** [comment]
The actual line seems to been removed in the link, but i added it where i'd expect and it seems to work fine!

**Comment by mirceaulinic** [comment]
Oh right, this is the line I was referring to: https://github.com/mirceaulinic/salt-sproxy/blob/develop/salt_sproxy/_runners/proxy.py#L283 - is this what you were looking at?
