### ISSUE TITLE
Improved documentation of the -b BATCH_SIZE option

### ISSUE THREAD

**Issue by aeciopires** [mirceaulinic/salt-sproxy#200]
**Describe the bug**

Hi, Mircea!

I still use salt-sproxy (in a Docker container) and I realized that by default it connects to 4 network assets in parallel.

Looking at the salt-sproxy options, I saw that you have the option:

```
-b BATCH_SIZE, --batch=BATCH_SIZE, --batch-size=BATCH_SIZE
The number of devices to connect to in parallel.
Default: 4
```

I increased it to 128, but it still connects to only 4 assets.

`alias salt-sproxy='f(){ time docker run --rm --network host -v $SALT_DIR_BASE/master:/etc/salt/master -v $SALT_PROXY_PILLAR_DIR:/etc/salt/pillar/ -v $SALT_PROXY_STATES_DIR:/srv/salt/ -v $TMP_DIR_BACKUPS:/tmp/backups/ -ti mirceaulinic/salt-sproxy:allinone-2020.10.2 salt-sproxy -b 128 $@; }; f'
`

When we talked via slack, you explained that the value of this option must be changed according to the amount of CPU that is available on the server that runs Salt-SProxy.

_mirceaulinic:  03 Dez - 10:49 AM
Hmm -b should be the argument to increase that
The value depends on how many CPUs you have on your machine
For example, on the server I have at work, we have 64 CPUs, so -b defaults to 64
But if you provide -b 128, then 128 it should use_

My server has only 4 CPU...

```
cat /proc/cpuinfo | grep processor
processor	: 0
processor	: 1
processor	: 2
processor	: 3
```

As a suggestion for improvement, could you add this information about the CPU in the next version of salt-sproxy, next to the -b option? This would make understanding this parameter more intuitive. 

Thank you and good day!

**Comment by mirceaulinic** [comment]
Closed via #201.
