### ISSUE TITLE
Question: Is globbing supported for pillar rosters?

### ISSUE THREAD

**Issue by vangourd** [mirceaulinic/salt-sproxy#91]
Versions:
`salt-sproxy 2020.2.0`
`Salt: 3000`

I have a pillar that looks like this.

**top.sls:**
```
base:
    - devices
    - proxy
```
**proxy.sls:**
```
proxy:
    proxytype: napalm
    driver: ios
    username: sproxy
    passwd: hunter2
    host: {{ opts.id}}.contoso.com
```

**devices.sls**
```
devices:
    - name: switch-alpha
    - name: switch-bravo
```

My `/etc/salt/master` has the following section:
```
# Pass in an alternative location for the salt-ssh roster file
#roster_file: /etc/salt/roster
roster_file: pillar
```

However if I run
`sudo salt-sproxy '*' test.ping`
```
No devices matched your target. Please review your tgt / tgt_type arguments, or the Roster data source
```

Am I doing something wrong?

This snippet from https://salt-sproxy.readthedocs.io/en/latest/roster.html
![image](https://user-images.githubusercontent.com/22150353/75071859-3c499580-54c4-11ea-966d-9b23e19d6b40.png). Seems to indicate what I'm doing should work like the salt cli. 

`sudo salt-sproxy \* --preview-target` results in the same **No devices** message as above. 

Running `sudo salt-run pillar.show_pillar` shows:
```
devices:
    |_
      ----------
      name:
          switch-alpha
    |_
      ----------
      name:
          switch-bravo
```

**Comment by mirceaulinic** [comment]
Hey @vangourd - it looks like you have `roster_file: pillar` in the master config, can you try with `roster: pillar` instead? Cheers!

**Comment by vangourd** [comment]
Works perfectly now!

Just to clarify I edited my `/etc/salt/master`  to have `roster: pillar` instead of `roster_file: pillar` and it worked right away.
